# Arrays

In [ ]:
2+2

4

In [ ]:
import numpy as np

In [ ]:
lista=[1,2,3,4]

In [ ]:
array = np.array(lista)
array

array([1, 2, 3, 4])

In [ ]:
array[3]

4

In [ ]:
lista2=[[1,2,3],[4,5,6],[7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
lista2[2]

[7, 8, 9]

In [ ]:
array2=np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2[2]

array([7, 8, 9])

# Arrays-arrange,zeros,ones,linspace,eye

In [ ]:
#arange genera un arran de n-1 elementos
array=np.arange(5)
array

array([0, 1, 2, 3, 4])

In [ ]:
array=np.arange(2,10)
array

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#incremento de n en p secuencias
array=np.arange(2,10,2)
array

array([2, 4, 6, 8])

In [ ]:
#método de zeros para rellear
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#matriz de ceros (renglones, columnas)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#matriz de unos
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#linspace; matriz de una sola dimensión, de n a p y R elementos
#los incrementos los hace entre el rango (n-p)/(R-1)
#ejemplo para (5,8,50) -> (5-8)/(50-1)=0.0612244
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [ ]:
np.linspace(3,9,20)

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [ ]:
#eye genera matrices identidades
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Numeros Aleatorios

In [ ]:
np.random.rand(5)

array([0.49644067, 0.02127514, 0.4114128 , 0.62869926, 0.43619152])

In [ ]:
#matriz de números aleatorios 2X3
np.random.rand(2,3)

array([[0.0328429 , 0.20699432, 0.31257439],
       [0.32676873, 0.26713924, 0.22016309]])

In [ ]:
#numeros aleatorios de distribución normal(0.1)
np.random.randn(4,5)

array([[ 0.05344622, -1.45049295, -0.93696833,  1.09001735,  1.15225458],
       [ 0.29448326,  0.27412949,  0.33729837,  0.67063051,  0.36249784],
       [ 0.12715862,  1.2752649 , -1.32555621,  1.00995752,  0.77890943],
       [ 0.57962631, -1.71996217, -0.82630828, -0.74975574,  0.39318007]])

# Numeros Aleatorios Enteros

In [ ]:
#Genera numeros enteros entre n y p-1 enteros
np.random.randint(1,20)

14

In [ ]:
#Generar 5 numeros
np.random.randint(1,20,5)

array([ 3,  5, 12, 10,  9])

# Reshape-Cambiar tamaño de los Arrays

In [ ]:
array=np.random.randint(1,100,25)
array

array([11, 37, 89, 28, 36, 16, 18, 11, 55, 81, 27, 32, 89, 87, 39,  3, 67,
       32, 86, 42, 37, 94, 76, 50, 21])

In [ ]:
matriz=array.reshape(5,5)
matriz

array([[11, 37, 89, 28, 36],
       [16, 18, 11, 55, 81],
       [27, 32, 89, 87, 39],
       [ 3, 67, 32, 86, 42],
       [37, 94, 76, 50, 21]])

In [ ]:
matriz2=array.reshape(5,6)
matriz2

ValueError: cannot reshape array of size 25 into shape (5,6)

In [ ]:
array2=np.random.randint(1,100,24)
array2

array([93, 50, 91,  4, 98,  4, 69, 78, 34, 84, 29, 60,  7, 33, 24, 94, 34,
       66, 73, 60, 13, 14, 42, 59])

In [ ]:
matriz3=array2.reshape(12,2)
matriz3

array([[93, 50],
       [91,  4],
       [98,  4],
       [69, 78],
       [34, 84],
       [29, 60],
       [ 7, 33],
       [24, 94],
       [34, 66],
       [73, 60],
       [13, 14],
       [42, 59]])

In [ ]:
array=np.random.randint(1,100,21)
matriz=array.reshape(3,7)
matriz

array([[34, 58,  2, 74,  9, 34, 43],
       [57, 44, 63, 14, 14, 64, 51],
       [74, 53, 28, 99, 93, 52, 89]])

# Valor Máximo y Mínimo

In [ ]:
array=np.random.randint(1,100,50)
array

array([50, 31, 37, 82, 77, 44, 39, 59, 29, 87, 66, 85, 42, 36, 74, 15, 43,
        6, 62, 17, 82, 78, 19,  6, 45, 64,  8, 14,  9, 78, 97, 98, 78, 17,
        7, 25, 61, 14, 22, 53, 28, 67, 66, 47, 73, 66, 41, 46, 55, 70])

In [ ]:
valor_maximo=array.max()
valor_maximo

98

In [ ]:
posicion_valor_max=array.argmax()
posicion_valor_max

31

In [ ]:
valor_min=array.min()
valor_min

6

In [ ]:
posicion_valor_min=array.argmin()
posicion_valor_min

17

In [ ]:
print(matriz)
print("")
print(matriz.min())
print(matriz.argmin())
print(matriz.max())
print(matriz.argmax())

[[34 58  2 74  9 34 43]
 [57 44 63 14 14 64 51]
 [74 53 28 99 93 52 89]]

2
2
99
17


# Indexacion en Arrays

In [ ]:
array=np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[0]

0

In [ ]:
array[-1]

9

In [ ]:
array[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#selección hacia adelante
array[5:]

array([5, 6, 7, 8, 9])

In [ ]:
#selección hacia atrás
array[:4]

array([0, 1, 2, 3])

In [ ]:
#Copiar un array
array2=array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array2[0]=100
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexacion Arrays de más de dos dimensiones

In [ ]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[0]

array([1, 2, 3])

In [ ]:
#selecciona dos filas/renglones
#las posiciones comienzan desde cero
array2=array[:2]
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array[0][0]

1

In [ ]:
array[1][1]

5

In [ ]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#seleccionamos por renglones
array[:,0]

array([1, 4, 7])

In [ ]:
array[:,2]

array([3, 6, 9])

In [ ]:
array[:,1]

array([2, 5, 8])

In [ ]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
array[:,2:]

array([[3],
       [6],
       [9]])

In [ ]:
array[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

# Selección por condición

In [ ]:
array=np.arange(0,14)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
condicion = array>5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True])

In [ ]:
sum(condicion)

8

In [ ]:
from numpy.lib.function_base import average
average(condicion)

0.5714285714285714

In [ ]:
#Aplicamos la condición al array
array[condicion]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
#elementos mayores que 5
array6=array[condicion]
array6

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
array[array<4]

array([0, 1, 2, 3])

In [ ]:
#Condiciones dentro de los arrays
array[array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12])

In [ ]:
array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False])

In [ ]:
from scipy import stats as st

In [ ]:
st.mode(array)

ModeResult(mode=0, count=1)

In [ ]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

# Operaciones sobre Arrays

In [ ]:
array=np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array+array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [ ]:
array-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
array2=np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
array2-array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
array2*array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [ ]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [ ]:
np.min(array)

0

In [ ]:
np.max(array)

9

# TAREA
Ejercicio 1

Crear una ista de números secuenciales con el valor mínimo de 10 y el máximo 39.
Convierte esta lista en una lista o matriz de 2 dimensiones (3 filas por 10 columnas).
Muestra por pantalla el valor del elemento de la esquina superior derecha de la matriz

Ejercicio 2

Crea un array de una dimensión con 9 valores enteros aleatorios entre 0 y 100.
Convierte ese array en una matriz de 2 dimensiones (3 filas y 3 columnas).
Muestra por pantalla el valor del elemento de la matriz de la esquina inferior derecha